require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/bairros", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Bairro. As you add validations to Bairro, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Bairro.create! valid_attributes
      get bairros_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      bairro = Bairro.create! valid_attributes
      get bairro_url(bairro)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_bairro_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      bairro = Bairro.create! valid_attributes
      get edit_bairro_url(bairro)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Bairro" do
        expect {
          post bairros_url, params: { bairro: valid_attributes }
        }.to change(Bairro, :count).by(1)
      end

      it "redirects to the created bairro" do
        post bairros_url, params: { bairro: valid_attributes }
        expect(response).to redirect_to(bairro_url(Bairro.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Bairro" do
        expect {
          post bairros_url, params: { bairro: invalid_attributes }
        }.to change(Bairro, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post bairros_url, params: { bairro: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested bairro" do
        bairro = Bairro.create! valid_attributes
        patch bairro_url(bairro), params: { bairro: new_attributes }
        bairro.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the bairro" do
        bairro = Bairro.create! valid_attributes
        patch bairro_url(bairro), params: { bairro: new_attributes }
        bairro.reload
        expect(response).to redirect_to(bairro_url(bairro))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        bairro = Bairro.create! valid_attributes
        patch bairro_url(bairro), params: { bairro: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested bairro" do
      bairro = Bairro.create! valid_attributes
      expect {
        delete bairro_url(bairro)
      }.to change(Bairro, :count).by(-1)
    end

    it "redirects to the bairros list" do
      bairro = Bairro.create! valid_attributes
      delete bairro_url(bairro)
      expect(response).to redirect_to(bairros_url)
    end
  end
end
