require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/eleitores", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Eleitor. As you add validations to Eleitor, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Eleitor.create! valid_attributes
      get eleitores_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      eleitor = Eleitor.create! valid_attributes
      get eleitor_url(eleitor)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_eleitor_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      eleitor = Eleitor.create! valid_attributes
      get edit_eleitor_url(eleitor)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Eleitor" do
        expect {
          post eleitores_url, params: { eleitor: valid_attributes }
        }.to change(Eleitor, :count).by(1)
      end

      it "redirects to the created eleitor" do
        post eleitores_url, params: { eleitor: valid_attributes }
        expect(response).to redirect_to(eleitor_url(Eleitor.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Eleitor" do
        expect {
          post eleitores_url, params: { eleitor: invalid_attributes }
        }.to change(Eleitor, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post eleitores_url, params: { eleitor: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested eleitor" do
        eleitor = Eleitor.create! valid_attributes
        patch eleitor_url(eleitor), params: { eleitor: new_attributes }
        eleitor.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the eleitor" do
        eleitor = Eleitor.create! valid_attributes
        patch eleitor_url(eleitor), params: { eleitor: new_attributes }
        eleitor.reload
        expect(response).to redirect_to(eleitor_url(eleitor))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        eleitor = Eleitor.create! valid_attributes
        patch eleitor_url(eleitor), params: { eleitor: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested eleitor" do
      eleitor = Eleitor.create! valid_attributes
      expect {
        delete eleitor_url(eleitor)
      }.to change(Eleitor, :count).by(-1)
    end

    it "redirects to the eleitores list" do
      eleitor = Eleitor.create! valid_attributes
      delete eleitor_url(eleitor)
      expect(response).to redirect_to(eleitores_url)
    end
  end
end
