


class Eleitor < ApplicationRecord
    self.implicit_order_column = :created_at

    # extends ...................................................................

    # includes ..................................................................
    audited
    acts_as_paranoid

    include Searchrable

    # security (i.e. attr_accessible) ...........................................


    # relationships .............................................................
            belongs_to :candidato, required: true
            belongs_to :bairro, required: true

    # validations ...............................................................
    # callbacks .................................................................
    # scopes ....................................................................
    # additional config .........................................................
    # class methods .............................................................
    # public instance methods ...................................................
    # protected instance methods ................................................
    # private instance methods ..................................................
end
